-- USUARIO ADMIN

-- ===== PASO 0 =====

-- ===== crear roles =====

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

-- ===== crear usuarios =====

CREATE USER PRY2205_USER1 IDENTIFIED BY "User1_2025_OK"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

CREATE USER PRY2205_USER2 IDENTIFIED BY "User2_2025_OK"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;


-- ===== crear permisos =====

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE SESSION TO PRY2205_USER2;

GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;

GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;

GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

--USER 1

-- Caso 1

CREATE PUBLIC SYNONYM S_LIBRO    FOR PRY2205_USER1.LIBRO;
CREATE PUBLIC SYNONYM S_EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE PUBLIC SYNONYM S_PRESTAMO FOR PRY2205_USER1.PRESTAMO;
CREATE PUBLIC SYNONYM S_EMPLEADO FOR PRY2205_USER1.EMPLEADO;

CREATE OR REPLACE PUBLIC SYNONYM S_LIBRO
FOR PRY2205_USER1.LIBRO;

CREATE OR REPLACE PUBLIC SYNONYM S_EJEMPLAR
FOR PRY2205_USER1.EJEMPLAR;

CREATE OR REPLACE PUBLIC SYNONYM S_PRESTAMO
FOR PRY2205_USER1.PRESTAMO;


-- luego de crear y poblar las datas con user 1 viene esto

GRANT SELECT ON PRY2205_USER1.LIBRO    TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EMPLEADO TO PRY2205_ROL_P;

GRANT CREATE VIEW TO PRY2205_USER2;

GRANT SELECT ON PRY2205_USER1.LIBRO    TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_USER2;

-- USER 2
-- Caso 2
--Paso 2.1 (PRY2205_USER2) Crear secuencia
DROP SEQUENCE SEQ_CONTROL_STOCK;
CREATE SEQUENCE SEQ_CONTROL_STOCK
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

DROP TABLE CONTROL_STOCK_LIBROS PURGE;

-- Paso 2.2 (PRY2205_USER2) Crear tabla CONTROL_STOCK_LIBROS
CREATE TABLE CONTROL_STOCK_LIBROS (
  ID_CONTROL NUMBER PRIMARY KEY,
  LIBRO_ID NUMBER(5),
  NOMBRE_LIBRO VARCHAR2(70),
  TOTAL_EJEMPLARES NUMBER,
  EN_PRESTAMO NUMBER,
  DISPONIBLES NUMBER,
  PORCENTAJE_PRESTAMO NUMBER(5,2),
  STOCK_CRITICO CHAR(1)
);


--Paso 2.3 (PRY2205_USER2) Insertar datos (consulta principal)

INSERT INTO CONTROL_STOCK_LIBROS
SELECT
  SEQ_CONTROL_STOCK.NEXTVAL AS ID_CONTROL,
  t.LIBRO_ID,
  t.NOMBRE_LIBRO,
  t.TOTAL_EJEMPLARES,
  t.EN_PRESTAMO,
  (t.TOTAL_EJEMPLARES - t.EN_PRESTAMO) AS DISPONIBLES,
  ROUND((t.EN_PRESTAMO / NULLIF(t.TOTAL_EJEMPLARES,0)) * 100, 2) AS PORCENTAJE_PRESTAMO,
  CASE
    WHEN (t.TOTAL_EJEMPLARES - t.EN_PRESTAMO) > 2 THEN 'S'
    ELSE 'N'
  END AS STOCK_CRITICO
FROM (
  SELECT
    l.LIBROID AS LIBRO_ID,
    l.NOMBRE_LIBRO,
    COUNT(e.EJEMPLARID) AS TOTAL_EJEMPLARES,
    COUNT(p.PRESTAMOID) AS EN_PRESTAMO
  FROM S_LIBRO l
  JOIN S_EJEMPLAR e
    ON e.LIBROID = l.LIBROID
  LEFT JOIN S_PRESTAMO p
    ON p.LIBROID = e.LIBROID
   AND p.EJEMPLARID = e.EJEMPLARID
   AND p.FECHA_INICIO >= ADD_MONTHS(TRUNC(SYSDATE,'YYYY'), -24)
   AND p.FECHA_INICIO <  TRUNC(SYSDATE,'YYYY')
   AND p.EMPLEADOID IN (150,180,190)
  GROUP BY l.LIBROID, l.NOMBRE_LIBRO
  ORDER BY l.LIBROID           -- 👈 el ORDER BY va AQUÍ
) t;

COMMIT;


SELECT COUNT(*) FROM CONTROL_STOCK_LIBROS;
SELECT* FROM CONTROL_STOCK_LIBROS;


-- USER 1
--caso 3

--caso 3
CREATE SYNONYM X_PRESTAMO FOR PRESTAMO;
CREATE SYNONYM X_ALUMNO   FOR ALUMNO;
CREATE SYNONYM X_CARRERA  FOR CARRERA;
CREATE SYNONYM X_REBAJA   FOR REBAJA_MULTA;
CREATE SYNONYM X_LIBRO FOR LIBRO;


CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
p.PRESTAMOID AS ID_PRESTAMO,
REGEXP_SUBSTR(a.NOMBRE,'^\S+')||' '||a.APATERNO AS NOMBRE_ALUMNO,
c.DESCRIPCION AS NOMBRE_CARRERA,
l.LIBROID AS ID_LIBRO,

LPAD(TO_CHAR(l.PRECIO,'$999G999G999'),18,' ') AS VALOR_LIBRO,

TO_CHAR(p.FECHA_TERMINO,'DD/MM/YYYY') AS FECHA_TERMINO,
TO_CHAR(p.FECHA_ENTREGA,'DD/MM/YYYY') AS FECHA_ENTREGA,

TRUNC(p.FECHA_ENTREGA-p.FECHA_TERMINO) AS DIAS_ATRASO,

LPAD(
  TO_CHAR(
    ROUND(TRUNC(p.FECHA_ENTREGA-p.FECHA_TERMINO)*(l.PRECIO*0.03)),
    '$999G999G999'
  ),
18,' '
) AS VALOR_MULTA,

NVL(r.PORC_REBAJA_MULTA,0)/100 AS PORCENTAJE_REBAJA_MULTA,

LPAD(
  TO_CHAR(
    ROUND(
      TRUNC(p.FECHA_ENTREGA-p.FECHA_TERMINO)*(l.PRECIO*0.03)*
      (1-NVL(r.PORC_REBAJA_MULTA,0)/100)
    ),
    '$999G999G999'
  ),
18,' '
) AS VALOR_REBAJADO

FROM X_PRESTAMO p
JOIN X_ALUMNO a ON a.ALUMNOID=p.ALUMNOID
JOIN X_CARRERA c ON c.CARRERAID=a.CARRERAID
JOIN X_LIBRO l ON l.LIBROID=p.LIBROID
LEFT JOIN X_REBAJA r ON r.CARRERAID=c.CARRERAID
WHERE p.FECHA_ENTREGA>p.FECHA_TERMINO
AND EXTRACT(YEAR FROM p.FECHA_TERMINO)=EXTRACT(YEAR FROM SYSDATE)-2
ORDER BY p.FECHA_ENTREGA DESC;





SELECT COUNT(*) FROM VW_DETALLE_MULTAS;
SELECT * FROM VW_DETALLE_MULTAS;


--caso 3.2
SELECT * FROM VW_DETALLE_MULTAS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALL'));

DROP INDEX IDX_PRESTAMO_MULTA;
DROP INDEX IDX_ALUMNO_CARRERA;

CREATE INDEX IDX_PRESTAMO_MULTA
ON PRESTAMO (ALUMNOID, LIBROID, FECHA_TERMINO, FECHA_ENTREGA);

CREATE INDEX IDX_ALUMNO_CARRERA
ON ALUMNO (ALUMNOID, CARRERAID);



SELECT * FROM VW_DETALLE_MULTAS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALL'));
